# Consolidated netlify.toml for PageDAO Hub


# Environment variable injection
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # This prevents npm from running extra commands

[build]
  command = "npx pnpm install && bash netlify-build.sh"
  functions = "packages/api/dist"
  publish = "packages/dashboard/dist"

# Redirect API endpoints to Netlify Functions
[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Original Frame endpoints
[[redirects]]
  from = "/frame"
  to = "/.netlify/functions/frame"
  status = 200

[[redirects]]
  from = "/image"
  to = "/.netlify/functions/image"
  status = 200

[[redirects]]
  from = "/trade"
  to = "/.netlify/functions/trade"
  status = 200

# Token API endpoints
[[redirects]]
  from = "/api/v1/token/price"
  to = "/.netlify/functions/token-price"
  status = 200

[[redirects]]
  from = "/api/v1/token/price/*"
  to = "/.netlify/functions/token-price/:splat"
  status = 200

# Liquidity API endpoints
[[redirects]]
  from = "/api/v1/liquidity/tvl"
  to = "/.netlify/functions/liquidity-tvl"
  status = 200

[[redirects]]
  from = "/api/v1/liquidity/tvl/*"
  to = "/.netlify/functions/liquidity-tvl/:splat"
  status = 200

# Redirect all other routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Function bundle settings
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ethers", "canvas", "@pagedao/core", "zod", "axios"]
  included_files = ["packages/core/dist/**", "packages/core/package.json"]
