[build]
  command = "yarn build"
  publish = "packages/dashboard/build"
  functions = "api"

# Environment variables available to all functions
[build.environment]
  NODE_VERSION = "18"
  REACT_APP_DEFAULT_THEME = "dark"
  REACT_APP_DEFAULT_TIMEFRAME = "24h"
  REACT_APP_REFRESH_INTERVAL = "60000"

# API paths
[[redirects]]
  from = "/api/token-prices"
  to = "/.netlify/functions/token-prices"
  status = 200

[[redirects]]
  from = "/api/historical-data"
  to = "/.netlify/functions/historical-data"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
