[build]
  command = "pnpm build"
  functions = "netlify/functions"
  publish = "packages/dashboard/dist"

[dev]
  framework = "#custom"
  command = "pnpm run dev:dashboard"
  port = 8888
  targetPort = 3000
  publish = "packages/dashboard/dist"
  autoLaunch = true

# Redirect API requests to Netlify Functions
[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200